# Generated by Django 6.0 on 2025-12-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_vida', '0002_alter_cursorealizado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='venta_garage/', verbose_name='Fotografía'),
        ),
    ]
